# Generated by Django 3.2.6 on 2021-08-08 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Posts_App', '0002_auto_20210808_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Album', 'verbose_name_plural': 'Album_list'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AddField(
            model_name='photo',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
